#!/bin/bash -e
# Copyright 2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

rm -f *.wav

./startup.sh
mv startup.wav _startup.wav
sox -D _startup.wav startup.wav gain -10

# Areas (Des major)

./area-layout.sh
mv area-layout.wav .area-layout.wav
sox -D .area-layout.wav area-layout.wav gain -20

./area-layout-double.sh
mv area-layout-double.wav .area-layout-double.wav
sox -D .area-layout-double.wav area-layout-double.wav gain -20

./area-layout-triple.sh
mv area-layout-triple.wav .area-layout-triple.wav
sox -D .area-layout-triple.wav area-layout-triple.wav gain -20




./popup.sh
mv popup.wav .popup.wav
sox -D .popup.wav popup.wav gain -22

./main-menu.sh
mv main-menu.wav _main-menu.wav
sox -D _main-menu.wav main-menu.wav gain -17.5


./message.sh
mv message.wav _message.wav
sox -D _message.wav message.wav gain -22


./done.sh
mv done.wav _done.wav
sox -D _done.wav done.wav gain -22

./inaccessible.sh
mv inaccessible.wav _inaccessible.wav
sox -D _inaccessible.wav inaccessible.wav gain -25

./copied.sh
mv copied.wav .copied.wav
sox -D .copied.wav copied.wav gain  -20

./cut.sh
mv cut.wav _cut.wav
sox -D _cut.wav cut.wav gain  -20

./paste.sh
mv paste.wav _paste.wav
sox -D _paste.wav paste.wav gain  -20

# List and text navigation, As major

./list-item.sh
mv list-item.wav _list-item.wav
sox -D _list-item.wav list-item.wav gain  -12

./empty-line.sh
mv empty-line.wav .empty-line.wav
sox -D .empty-line.wav empty-line.wav gain  -22.5

./list-item-important.sh
mv list-item-important.wav .list-item-important.wav
sox -D .list-item-important.wav list-item-important.wav gain  -25

./bounds.sh
mv bounds.wav _bounds.wav
sox -D _bounds.wav bounds.wav gain -10

# misc

./commander-location.sh
mv commander-location.wav .commander-location.wav
sox -D .commander-location.wav commander-location.wav gain -22.5

rm -f _*.wav .*.wav


# For compatibility
cp list-item-important.wav desktop-item.wav
cp list-item-important.wav main-menu-item.wav
cp bounds.wav list-bounds.wav
cp bounds.wav text-bounds.wav
