#!/bin/bash -e
# Copyright 2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

./announce-popup.sh
mv announce-popup.wav _announce-popup.wav
sox -D _announce-popup.wav announce-popup.wav gain -22

./done.sh
mv done.wav _done.wav
sox -D _done.wav done.wav gain -22

./inaccessible.sh
mv inaccessible.wav _inaccessible.wav
sox -D _inaccessible.wav inaccessible.wav gain -25

./copy.sh
mv copy.wav _copy.wav
sox -D _copy.wav copy.wav gain  -20

./cut.sh
mv cut.wav _cut.wav
sox -D _cut.wav cut.wav gain  -20

./paste.sh
mv paste.wav _paste.wav
sox -D _paste.wav paste.wav gain  -20

./list-item.sh
mv list-item.wav _list-item.wav
sox -D _list-item.wav list-item.wav gain  -12

./list-item-important.sh
mv list-item-important.wav _list-item-important.wav
sox -D _list-item-important.wav list-item-important.wav gain  -20

./bounds.sh
mv bounds.wav _bounds.wav
sox -D _bounds.wav bounds.wav gain -25

rm -f _*.wav


# For compatibility
cp copy.wav copied.wav
cp list-item-important.wav desktop-item.wav
cp list-item-important.wav main-menu-item.wav
cp bounds.wav list-bounds.wav
cp bounds.wav text-bounds.wav



