#!/bin/bash -e

THIS="${0##*/}"
JAR="$TMPDIR/jenkins-cli.jar"

[ -z "$JENKINS_ADMIN_PASSWD_FILE" ] && echo "ERROR: $THIS: Please set the JENKINS_ADMIN_PASSWD_FILE environment variable" >&2 && exit 1
PASSWD="$(cat $JENKINS_ADMIN_PASSWD_FILE)"

if ! [ -r "$JAR" ]; then
    pushd $TMPDIR > /dev/null
    wget -q http://localhost:8080/jnlpJars/jenkins-cli.jar 
    popd > /dev/null
fi


exec java -jar "$JAR" -auth "admin:$PASSWD" "$@"
