version: '3.1'                                                                                            
networks:
  docker:

services:                                                                                                 
  jenkins:                                                                                                  
    image: jenkinsci/blueocean                                                                                
    restart: always                                                                                           
    networks:                                                                                                 
      - docker                                                                                                  
    ports:                                                                                                    
      - 8080:8080                                                                                               
      - 50000:50000                                                                                             
    volumes:
      - /wrk/jenkins/data:/var/jenkins_home                                                                          
      - /wrk/jenkins/certs:/certs/client:ro                                                                   
      - /wrk/jenkins/home:/home                                                                                             
    environment:                                                                                              
      - DOCKER_HOST=tcp://docker:2376                                                                           
      - DOCKER_CERT_PATH=/certs/client                                                                          
      - DOCKER_TLS_VERIFY=1

  dind:                                                                                                     
    image: docker:dind                                                                                        
    privileged: true                                                                                          
    restart: always                                                                                           
    networks:                                                                                                 
      docker:                                                                                                   
    hostname: docker                                                                                                  
    ports:                                                                                                    
      - 2376:2376                                                                                               
    volumes:
      - /wrk/jenkins/data:/var/jenkins_home                                                                          
      - /wrk/jenkins/certs:/certs/client                                                                      
      - /wrk/jenkins/home:/home                                                                                             
    environment:                                                                                              
      - DOCKER_TLS_CERTDIR=/certs                                                                               
