#!/bin/sh -e
# The script to fetch all Luwrain source materials to local machine

APPS=app-notepad

cd ../..
for i in luwrain linux $APPS; do
    git clone https://github.com/luwrain/$i.git
done

mkdir lib-env lib-app

ln -s ../lib-env luwrain/lib
ln -s ../lib-env linux/lib
for i in $APPS; do
    ln -s ../lib-app $i/lib
done



ln -s ../base/jar/luwrain-base.jar lib-env/luwrain-base.jar
ln -s ../base/jar/luwrain-base.jar lib-app/luwrain-base.jar
ln -s ../luwrain/jar/luwrain.jar lib-app/luwrain.jar
