#!/bin/sh -e
# The script to fetch all Luwrain source materials to local machine

APPS='app-notepad app-news app-fetch app-commander'

cd ../..
for i in luwrain linux pim $APPS; do
    git clone https://github.com/luwrain/$i.git
done

mkdir lib-env lib-app

ln -s ../lib-env luwrain/lib
ln -s ../lib-env linux/lib
for i in $APPS; do
    ln -s ../lib-app $i/lib
done
ln -s ../lib-app pim/lib

ln -s ../base/jar/luwrain-base.jar lib-env/luwrain-base.jar
ln -s ../base/jar/luwrain-base.jar lib-app/luwrain-base.jar
ln -s ../luwrain/jar/luwrain.jar lib-app/luwrain.jar
ln -s ../pim/jar/luwrain-pim.jar lib-app/luwrain-pim.jar

wget http://download.luwrain.org/data/luwrain-data.zip
wget http://download.luwrain.org/lib/luwrain-lib.zip

for i in data lib; do
    unzip luwrain-$i.zip
    rm -f luwrain-$i.zip
done

cd lib
for i in *.jar; do
    ln -s ../lib/$i ../lib-env/$i
    ln -s ../lib/$i ../lib-app/$i
done


echo 
echo Everything is fetched successfully!
