#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

DIR="$(pwd)"
DEST_DIR="$DIR/debian/luwrain/usr/share/luwrain"

cd base/scripts
mkdir -p "$DEST_DIR/bin"

cat <<EOF > "$DEST_DIR/bin/luwrain"
#!/bin/bash -e
# Runs the LUWRAIN platform for the blind

cd /usr/share/luwrain
exec java --module-path /usr/share/openjfx/lib --add-modules javafx.controls -jar jar/luwrain-base.jar "$@"
EOF
chmod 755 "$DEST_DIR/bin/luwrain"

./lwr-basedirs-linux "$DEST_DIR"
