#!/bin/bash -e

. init.sh

TAG="$1"
[ -z "$TAG" ] && echo "$THIS:no tag given" >&2 && exit 1

lwr-list-repos | while read l; do
    echo "Tagging $l"
    pushd $l  > /dev/null
    git tag "$TAG" > /dev/null
    git push --tags origin > /dev/null
    popd		 > /dev/null
done			
