#!/bin/bash -e

. init.sh

make_link()
{
    if ! [ -e "$2" ]; then
	ln -s "$1" "$2"
    fi
}

# Stages directories
for i in 1 2 3 4; do 
    if [ -d "lib-stage$i" ]; then
	find lib-stage$i -type l -delete
	rmdir lib-stage$i 
    fi
done
for i in 1 2 3 4; do mkdir -p lib-stage$i; done
cd lib-stage1
for i in "$SRC_DIR/lib"/*.jar; do ln -s $i; done 
ln -s "$SRC_DIR/base/jar/luwrain-base.jar"
cd ../lib-stage2
for i in "$SRC_DIR/lib-stage1"/*.jar; do ln -s $i; done 
ln -s "$SRC_DIR/luwrain/jar/luwrain.jar"
for i in linux windows; do
    ln -s "$SRC_DIR/$i/jar/luwrain-$i.jar"
done
cd ../lib-stage3
for i in "$SRC_DIR/lib-stage2"/*.jar; do ln -s $i; done 
for i in $COMPONENTS; do
if ! [ -L luwrain-$i.jar ]; then
    ln -s "$SRC_DIR/$i/jar/luwrain-$i.jar"
fi
done
cd ../lib-stage4
for i in "$SRC_DIR/lib-stage3"/*.jar; do ln -s $i; done 
for i in $APPS; do ln -s "$SRC_DIR/app-$i/jar/luwrain-app-$i.jar"; done
for i in $EXTENSIONS; do ln -s "$SRC_DIR/extensions/$i/jar/luwrain-ext-$i.jar"; done
cd ..

# Repositories links

for i in luwrain interaction-javafx; do
    make_link "$SRC_DIR/lib-stage1" "$i"/lib
done
for i in browser extensions io linux packs pim reader player studio windows; do
    make_link "$SRC_DIR/lib-stage2" $i/lib
done
for i in $APPS; do
    make_link "$SRC_DIR/lib-stage3" app-$i/lib
done
make_link "$SRC_DIR/lib-stage4" i18n/lib
