#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

TEMP_DIR=$(mktemp -d /tmp/.nightly-XXXXXX)

if [ "$1" == '--tmpfs' ]; then
    echo "Creating tmpfs at $TEMP_DIR"
    sudo mount -t tmpfs -o size=20g tmpfs "$TEMP_DIR"
else
    echo "Working in $TEMP_DIR"
fi

rm -f /tmp/nightly
ln -s $TEMP_DIR /tmp/nightly

cd $TEMP_DIR

echo 'Downloading files'
git clone --recursive  https://github.com/luwrain/parent/ &> log
mv parent src
cd src/base/scripts
./lwr-prepare &>> ../../../log

DEST="luwrain-nightly-`date -I`"
./lwr-dist-src $TEMP_DIR/$DEST
pushd "$TEMP_DIR" > /dev/null
tar -c "$DEST/" | xz > "$DEST.tar.xz"
sha1sum "$DEST.tar.xz" > sha1.txt
popd > /dev/null

echo Compiling sources
./lwr-build &> ../../../log


echo Packing for Linux
./lwr-dist-linux $TEMP_DIR/linux
for i in x64; do
    DEST=luwrain-linux-"$i"-nightly-"`date -I`"
    mv "$TEMP_DIR/linux/$i" "$TEMP_DIR/$DEST"
    pushd "$TEMP_DIR" > /dev/null
    tar -c "$DEST/" | xz > "$DEST.tar.xz"
    sha1sum "$DEST.tar.xz" >> sha1.txt
    popd > /dev/null
done
rmdir "$TEMP_DIR/linux"

echo Packing for Microsoft Windows
./lwr-dist-win $TEMP_DIR/win
for i in x64; do
    DEST=luwrain-windows-"$i"-nightly-"`date -I`"
    mv "$TEMP_DIR/win/$i" "$TEMP_DIR/$DEST"
    pushd "$TEMP_DIR" > /dev/null
    zip -r "$DEST.zip" "$DEST" > /dev/null
    sha1sum "$DEST.zip" >> sha1.txt
    popd > /dev/null
done
for i in x64; do
    DEST=luwrain-windows-installer-"$i"-nightly-"`date -I`"
    mv "$TEMP_DIR/win/installer-$i" "$TEMP_DIR/$DEST"
    pushd "$TEMP_DIR" > /dev/null
    zip -r "$DEST.zip" "$DEST" > /dev/null
    sha1sum "$DEST.zip" >> sha1.txt
    popd > /dev/null
done
rmdir $TEMP_DIR/win

echo Packing the standalone version
DEST=luwrain-standalone-nightly-`date -I`
./lwr-dist-standalone "$TEMP_DIR/$DEST"
pushd "$TEMP_DIR" > /dev/null
tar -c $DEST/ | xz > $DEST.tar.xz
sha1sum "$DEST.tar.xz" >> sha1.txt
popd > /dev/null

#./lwr-dist-iso $TEMP_DIR/iso
# ISO
#DEST=luwrain-iso-nightly-"`date -I`"
#mv "$TEMP_DIR/iso" "$TEMP_DIR/$DEST"
#pushd "$TEMP_DIR" > /dev/null
#tar -c "$DEST/" | gzip > "$DEST.tar.gz"
#sha1sum "$DEST.tar.gz" >> sha1.txt
#rm -rf "$TEMP_DIR/$DEST"

cd "$TEMP_DIR"
RELEASE_DIR=~/nightly-`date -I`
if [ -d "$RELEASE_DIR" ]; then
    echo "${0##*/}:$RELEASE_DIR exists, skipping its creation"
    exit 0
fi

mkdir -p "$RELEASE_DIR"
mv *.txt *.xz *.zip "$RELEASE_DIR"
if [ -r /tmp/lwr-report/junit-noframes.html ]; then
    cp /tmp/lwr-report/junit-noframes.html "$RELEASE_DIR/junit-report.html"
fi
rm -f "$RELEASE_DIR/log.txt"

cat <<EOF > "$RELEASE_DIR/version.php"
<?php
function lwr_nightly_latest_date()
{
return "$(date -I)";
}
?>
EOF

echo 'OK!'
