#!/bin/bash -e
# Copyright 2012-2021 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

DIST_DIR="$1"
DEST_DIR="$2"
[ -z "$DIST_DIR" ] && echo "$THIS: no source dir given" >&2 && exit 1
[ -z "$DEST_DIR" ] && echo "$THIS: no dest dir given" >&2 && exit 1

mkdir -p $DEST_DIR
cp -r $DIST_DIR/. $DEST_DIR
lwr-custom-base-linux $DEST_DIR books
cd $DEST_DIR

for i in $LINUX_ARCH; do

        pushd $i/lib/app/jar > /dev/null
	for k in browser publisher studio pim packs; do
	    rm -f luwrain-$k.jar
	done
	rm -f luwrain-app* *dm*.jar *tsulib*.jar *-edu*.jar
	popd > /dev/null

	pushd $i/lib/app/lib > /dev/null
	rm -f junit*.jar twitter*.jar vk-sdk*.ja h2-* r.jar javax.mail*.jar nitrite*.jar pdfbox*.jar rome*.jar sqlite*.jar tdlib*.jar 
	popd > /dev/null

	pushd $i/lib/app/data/js > /dev/null
	rm commander*.js -f studio-*.js reader-ms*.js clock*.js linux*.js  math*.js message*.js music*.js notepad*.js pim*.js pm*.js tsulib*.js util-keyboard*.js web-cbrf*.js web-ddg*.js wi-disks*.js mail.js *edu*.js
	popd > /dev/null

    pushd $i/lib/app/data/properties > /dev/null
    sed -i -e s/'org.luwrain.core.shell.desktop.Desktop'/'org.luwrain.app.reader.App'/ luwrain.properties
    popd > /dev/null

    pushd $i > /dev/null
    cp $SRC_DIR/base/AUTHORS $SRC_DIR/base/LICENSE ./
    popd > /dev/null
done
