#!/bin/bash -e

. init.sh

mkdir -p ~/luwrain

cd ~/luwrain
mkdir jar news
ln -s "$SRC_DIR/linux/src/jni" jni
ln -s "$SRC_DIR/data" data
ln -s "$SRC_DIR"/lib lib
ln -s "$SRC_DIR/linux/common.sh" ~/luwrain/luwrain.sh
ln -s "$SRC_DIR/linux/luwrain.conf.def" ~/luwrain/luwrain.conf.def
ln -s "$SRC_DIR/linux/setup.sh" ~/luwrain/setup.sh
ln -s "$SRC_DIR/registry/default.linux" registry
ln -s "$SRC_DIR/registry/default.news.ru" news/ru
ln -s "$SRC_DIR/hsqldb" hsqldb

#Jars
ln -s "$SRC_DIR/luwrain/jar/luwrain.jar" jar/luwrain.jar
for i in base linux pim doctree interaction-javafx; do
    ln -s "$SRC_DIR/$i/jar/luwrain-$i.jar" jar/luwrain-$i.jar
done 

for i in $APPS; do
ln -s "$SRC_DIR"/app-$i/jar/luwrain-app-$i.jar jar/luwrain-app-$i.jar
done

for i in $LANGS; do
ln -s "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar/luwrain-lang-$i.jar
done

for i in $EXTENSIONS; do
ln -s "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar/luwrain-ext-$i.jar
done
