#!/bin/bash -e

. init.sh

if [ -n "$1" ]; then 
    DEST_DIR="$1"
else
    DEST_DIR=/tmp/luwrain-linux
fi

mkdir -p $DEST_DIR

cd $DEST_DIR
mkdir -p jar jni i18n registry/org/luwrain
cp -r "$SRC_DIR/data" data
cp -r "$SRC_DIR"/lib lib
cp  "$SRC_DIR/linux/luwrain.sh" luwrain.sh

for i in base; do
    cp -r "$SRC_DIR/registry/$i/." registry/org/luwrain
done
for i in "$SRC_DIR/registry"/i18n.*; do
    D=i18n/"${i##*.}/org/luwrain"
mkdir -p "$D"
    cp -r "$i/." "$D"
done

#Jars
for i in $BASIC_COMPONENTS $LINUX_COMPONENTS; do
    cp "$SRC_DIR/$i/jar/luwrain-$i.jar" jar
done

for i in $APPS; do
    cp "$SRC_DIR"/app-$i/jar/luwrain-app-$i.jar jar
done

for i in $LANGS; do
    cp "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar
done

for i in $EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done

cp -r "$SRC_DIR"/sqlite .
cp -r "$SRC_DIR/linux/src/jni" jni-src
cd jni-src
rm -f *.so *.o .gitignore
cd ..
zip -r jni-src.zip jni-src/ > /dev/null
rm -rf jni-src
cp -r "$SRC_DIR/ubuntu-precompiled/." jni
echo "luwrain.class.os = org.luwrain.linux.Linux" >> data/properties/"$PROPERTIES_FILE"
