#!/bin/bash -e

. init.sh

if [ -n "$1" ]; then 
    DEST_DIR="$1"
else
    DEST_DIR=/tmp/luwrain-sdk
fi

mkdir -p $DEST_DIR
./lwr-mk-api "$DEST_DIR/javadoc"
cd $DEST_DIR

mkdir jar
cp "$SRC_DIR/luwrain/jar/luwrain.jar" jar
for i in $SDK_JARS; do
cp "$SRC_DIR/$i/jar/luwrain-$i.jar" jar
done

