#!/bin/bash -e

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"

cd "$SRC_DIR/base/scripts"
./lwr-mk-api "$DEST_DIR/javadoc"
cd $DEST_DIR

mkdir jar
cp "$SRC_DIR/luwrain/jar/luwrain.jar" jar
for i in $SDK_JARS; do
cp "$SRC_DIR/$i/jar/luwrain-$i.jar" jar
done

