#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

WIN_APPS='commander contacts mail news notepad telegram twitter viewer vk'
WIN_EXTENSIONS='mssapi plmp3 rhvoice'
WIN_PROPERTIES='luwrain player reader windows'

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory" >&2 && exit 1
mkdir -p "$DEST_DIR"

cp -r release/jar "$DEST_DIR"
cp release/lib/*.jar "$DEST_DIR/jar"
mkdir -p "$DEST_DIR/data"
cp -r data/sounds "$DEST_DIR/data"
cp -r extensions/js "$DEST_DIR/data/js"
cd "$DEST_DIR"

#Jars
for i in $WIN_APPS; do
    cp "$SRC_DIR"/app-$i/jar/luwrain-app-$i.jar jar
done
for i in $LANGS; do
    cp "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar
done
for i in $WIN_EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done

#Registry
pushd "$SRC_DIR/registry" > /dev/null
./lwr-reg-compile win "$DEST_DIR/data"
popd > /dev/null

#Properties
mkdir data/properties
for i in $WIN_PROPERTIES; do
    cp -r "$SRC_DIR/$i/properties/." data/properties
done
cat <<EOF > data/properties/release.properties
luwrain.version = $VERSION
luwrain.registry.version = $REGISTRY_VERSION
luwrain.build.date = $(date -I)
EOF

#luwrain.bat
cat <<EOF > luwrain.bat
rem Runs LUWRAIN with the locally installed (not embedded) JRE

javaw -cp jar\luwrain-base.jar
EOF
