#!/bin/bash -e
# Must not be invoked directly, called by lwr-distr-iso

. init.sh

ARCH="$1"
[ -z "$ARCH" ] && echo "$THIS:no arch given" >&2 && exit 1
LANG="$2"
[ -z "$LANG" ] && echo "$THIS:no lang given" >&2 && exit 1
DEST_DIR="$3"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1

cd $DEST_DIR
mkdir app
pushd app > /dev/null
mkdir -p jar
for i in lib data; do
    cp -r "$SRC_DIR/$i" "$i"
done
rm -rf data/scripts data/properties

#Jars
cp "$SRC_DIR/luwrain/jar/luwrain.jar" jar
for i in $ISO_COMPONENTS; do
    cp "$SRC_DIR/$i/jar/luwrain-$i.jar" jar
done
for i in $ISO_APPS; do
    cp "$SRC_DIR"/app-$i/jar/luwrain-app-$i.jar jar
done
for i in $LANG; do
    cp "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar
done
for i in $ISO_EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done
if [ -d ~/.luwrain/dev/jar/ ]; then
    for i in ~/.luwrain/dev/jar/*; do
	cat $i > jar/"$(basename "$i")"
    done
fi

pushd "$SRC_DIR/registry" > /dev/null
./lwr-reg-compile iso "$DEST_DIR/app/data"
popd > /dev/null

#JavaScript
cp -r "$SRC_DIR/extensions/js" data/js
if [ -d ~/.luwrain/dev/js/ ]; then
    for i in ~/.luwrain/dev/js/*; do
	cat $i > data/js/"$(basename "$i")"
    done
fi
#Text extensions
cp -r "$SRC_DIR/extensions/text" data/text
popd > /dev/null
cp -r "$SRC_DIR/binary/linux$ARCH/." .

#properties
mkdir app/data/properties
for i in $ISO_PROPERTIES; do
    cp -r "$SRC_DIR/$i/properties/." app/data/properties
done
cat <<EOF > app/data/properties/release.properties
# General release information
luwrain.version = $VERSION
luwrain.registry.version=$REGISTRY_VERSION
luwrain.build.date = $(date -I)
EOF

#scripts
mkdir -p app/data/scripts
for i in $ISO_SCRIPTS; do
    cp -r "$SRC_DIR/$i/scripts/." app/data/scripts
done
chmod +x app/data/scripts/*
