#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

lwr-list-repos | while read l; do
    echo "Pushing $l"
    pushd $l  > /dev/null
    git push origin "$@" &> /dev/null
    popd		 > /dev/null
done			

echo OK
