#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

DIST_DIR="$1"
DEST_DIR="$2"
[ -z "$DIST_DIR" ] && echo "$THIS: no source dir given" >&2 && exit 1
[ -z "$DEST_DIR" ] && echo "$THIS: no dest dir given" >&2 && exit 1

mkdir -p "$DEST_DIR"
cp -r "$DIST_DIR/." "$DEST_DIR"
lwr-custom-base-win "$DEST_DIR" dl
cd "$DEST_DIR"

ARCH=64
cat "$SRC_DIR/windows/installer/dl/main.ico" > $ARCH/dl.ico

pushd $ARCH/jar > /dev/null
for k in books studio pim packs edu-algo app-news app-mail app-contacts app-commander app-telegram app-twitter app-vk; do
    rm -f luwrain-$k.jar
done
rm -f *tsulib*.jar
popd > /dev/null

pushd $ARCH/lib > /dev/null
rm -f junit*.jar twitter*.jar vk-sdk*.jar sqlite*.jar
popd > /dev/null

pushd $ARCH/data/properties > /dev/null
sed -i -e s/'org.luwrain.core.shell.desktop.Desktop'/'ru.dl.app.App'/ luwrain.properties
popd > /dev/null

pushd $ARCH/data/js > /dev/null
rm -f studio-*.js reader-ms*.js edu-*.js clock*.js
popd > /dev/null

pushd $ARCH/data/sounds/schemes/pragmatic > /dev/null
#rm -f startup.wav
#wget -q http://download.luwrain.org/media/startup/dm.wav
#mv dm.wav startup.wav
popd > /dev/null

lwr-custom-base-win-legacy "$DEST_DIR" dl
lwr-win-installer dl 64 $DEST_DIR/64 $DEST_DIR/installer64
lwr-win-installer dl 32 $DEST_DIR/32 $DEST_DIR/installer32
