#!/bin/bash -e
# Must not be invoked directly, called by lwr-distr-iso

. init.sh

ARCH="$1"
[ -z "$ARCH" ] && echo "$THIS:no arch given" >&2 && exit 1
LANG="$2"
[ -z "$LANG" ] && echo "$THIS:no lang given" >&2 && exit 1
DEST_DIR="$3"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1

cd $DEST_DIR

mkdir -p jar
for i in lib data; do
    cp -r "$SRC_DIR/$i" "$i"
done
rm -rf data/scripts data/properties

#Jars
cp "$SRC_DIR/luwrain/jar/luwrain.jar" jar
for i in $ISO_COMPONENTS; do
    cp "$SRC_DIR/$i/jar/luwrain-$i.jar" jar
done
for i in $ISO_APPS; do
    cp "$SRC_DIR"/app-$i/jar/luwrain-app-$i.jar jar
done
for i in $LANG; do
    cp "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar
done
for i in $ISO_EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done

pushd "$SRC_DIR/registry" > /dev/null
./lwr-reg-compile iso "$DEST_DIR/data"
popd > /dev/null

#JavaScript
cp -r "$SRC_DIR/extensions/js" data/js
#Text extensions
cp -r "$SRC_DIR/extensions/text" data/js

#properties
mkdir data/properties
for i in $ISO_PROPERTIES; do
    cp -r "$SRC_DIR/$i/properties/." data/properties
done
cat <<EOF > data/properties/release.properties

# General release information
luwrain.version = $VERSION
luwrain.build.date = $(date -I)
EOF

#scripts
mkdir -p data/scripts
for i in $ISO_SCRIPTS; do
    cp -r "$SRC_DIR/$i/scripts/." data/scripts
done
chmod +x data/scripts/*

#desktop
cat <<EOF  >> data/registry.ru.dat
DIR org/luwrain/desktop/unirefs
FILE strings.txt
"000001" = "empty:"
"000002" = "section:Добро пожаловать в LUWRAIN!"
"000003" = "empty:"
"000004" = "command:browser"
"000005" = "command:studio"
"000006" = "command:twitter"
"000007" = "command:player"
"000008" = "command:commander"
"000009" = "empty:"
"000010" = "section:Подсказка"
"000011" = "empty:"
"000012" = "static:Нажмите клавишу главного меню на клавиатуре для открытия главного меню LUWRAIN"
"000013" = "empty:"
"000014" = "section:О программе"
"000015" = "empty:"
"000016" = "static:LUWRAIN $VERSION (сборка $(date -I))"
"000017" = "link:Наш сайт\: luwrain.org:url:http://luwrain.org/?mode=adapted&lang=ru"
"000018" = "static:Авторы: Алексей Голошумов, Михаил Пожидаев и Елена Теплых"
EOF

cat <<EOF  >> data/registry.en.dat
DIR org/luwrain/desktop/unirefs
FILE strings.txt
"000001" = "empty:"
"000002" = "section:Welcome to LUWRAIN!"
"000003" = "empty:"
"000004" = "command:browser"
"000005" = "command:studio"
"000006" = "command:twitter"
"000007" = "command:player"
"000008" = "command:commander"
"000009" = "empty:"
"000010" = "section:Hint"
"000011" = "empty:"
"000012" = "static:Press the main menu button on your keyboard to open the LUWRAIN main menu"
"000013" = "empty:"
"000014" = "section:About LUWRAIN"
"000015" = "empty:"
"000016" = "static:LUWRAIN $VERSION (build $(date -I))"
"000017" = "link:Out website\: luwrain.org:url:http://luwrain.org/?mode=adapted&lang=ru"
"000018" = "static:Our team: Alexey Goloshumov, Michael Pozhidaev, Elena Teplykh"
EOF

cp -r "$SRC_DIR/precompiled/linux-x86-$ARCH/." .
