#!/bin/bash -e

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p $DEST_DIR
cd $DEST_DIR

# Portable 32-bit
mkdir 32
cd 32
cp -r "$SRC_DIR/binary/win32/." .
lwr-basedirs-win "$DEST_DIR/32/app"
cp -r "$SRC_DIR/base/txt/windows/." .
cat <<EOF > ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
32-bit release for Microsoft Windows
EOF
cd ..

# Installer 32-bit
mkdir installer32
cd installer32
cp -r "$SRC_DIR/binary/wininstaller/." .
mkdir -p iss-fix/x32/Luwrain
cp -r "$SRC_DIR/binary/win32/." ./iss-fix/x32/Luwrain/
lwr-basedirs-win "$DEST_DIR/installer32/iss-fix/x32/Luwrain/app"
cp -r "$SRC_DIR/windows/installer/nightly/." ./
cp "$SRC_DIR/windows/installer"/*.iss iss-fix
sed -i -e s/LUWRAIN_VERSION/$VERSION/ iss-fix/*.iss
cd ..
