#!/bin/bash -e

. init.sh

if [ -n "$1" ]; then 
    DEST_DIR="$1"
else
    DEST_DIR=/tmp/lwr-api
fi

jars()
{
    find "$1" -iname '*.jar' | 
    while read l; do
	echo -n "$l:"
    done
    echo
}

rm -rf "$DEST_DIR"
mkdir "$DEST_DIR"
cd "$DEST_DIR"

javadoc -classpath "$(jars "$SRC_DIR"/lib-stage4)" \
$(find "$SRC_DIR"/luwrain/src/main/java/ -iname '*.java') \
$(find "$SRC_DIR"/base/src/main/java/ -iname '*.java') > /dev/null \
$(find "$SRC_DIR"/pim/src/main/java/ -iname '*.java') > /dev/null \
$(find "$SRC_DIR"/app-browser/src/main/java/ -iname '*.java') > /dev/null \
$(find "$SRC_DIR"/doctree/src/main/java/ -iname '*.java') > /dev/null 
