#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS: no destination directory" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"

mkdir -p "$DEST_DIR"
lwr-basedirs-linux "$DEST_DIR"
cp -r "$SRC_DIR/binary/linux64/lib/app/rhvoice" "$DEST_DIR"
cd "$DEST_DIR/"
rm -rf data/registry*
pushd "$SRC_DIR/registry" > /dev/null
./lwr-reg-compile iso "$DEST_DIR/data"
popd > /dev/null
pushd rhvoice/data > /dev/null
pushd voices > /dev/null
rm -rf $(ls | grep -v aleksandr)
popd > /dev/null
pushd languages > /dev/null
rm -rf $(ls | grep -v Russian  | grep -v English)
popd > /dev/null
popd > /dev/null
cat <<EOF > ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
EOF
