#!/bin/bash -e
# Copyright 2012-2021 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

cd "$SCRIPTS_DIR"

./lwr-list-repos | while read l; do
    pushd "$SRC_DIR/$l" > /dev/null
    echo `pwd`
    popd > /dev/null
done
