#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

[ -d ~/luwrain ] && echo ~/luwrain" exists, delete it explicitly and try again" >&2 && exit 1

mkdir -p ~/luwrain

cd ~/luwrain
mkdir jar data
ln -s "$SRC_DIR/lib" lib
ln -s "$SRC_DIR/linux/luwrain.sh" ~/luwrain/luwrain.sh

#Jars
ln -s "$SRC_DIR/luwrain/jar/luwrain.jar" jar/luwrain.jar
for i in $LINUX_COMPONENTS; do
    ln -s "$SRC_DIR/$i/jar/luwrain-$i.jar" jar/luwrain-$i.jar
done 
for i in $LINUX_APPS; do
ln -s "$SRC_DIR"/app-$i/jar/luwrain-app-$i.jar jar/luwrain-app-$i.jar
done
for i in $LINUX_LANGS; do
ln -s "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar/luwrain-lang-$i.jar
done
for i in $LINUX_EXTENSIONS; do
ln -s "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar/luwrain-ext-$i.jar
done

cd data
mkdir properties scripts
ln -s "$SRC_DIR/data/sounds" sounds
ln -s "$SRC_DIR/extensions/js" js
for i in $LINUX_PROPERTIES; do
    cp -r "$SRC_DIR/$i/properties/." properties
done
for i in $LINUX_SCRIPTS; do
    for l in "$SRC_DIR/$i/scripts"/*; do
	ln -s "$l" scripts
	done
done



cd "$SRC_DIR/registry"
./lwr-reg-compile linux ~/luwrain/data
cd ..
cp -r binary/linux64/. ~/luwrain
