#!/bin/bash -e

TEMP_DIR=$(mktemp -d)

[ -e /tmp/nightly ] && rm -f /tmp/nightly
ln -s  $TEMP_DIR /tmp/nightly
SRC_RES_DIR=luwrain-nightly-$(date --iso-8601)
LINUX_RES_DIR=luwrain-linux-nightly-$(date --iso-8601)
ISO_RES_DIR=luwrain-iso-nightly-$(date --iso-8601)
SDK_RES_DIR=luwrain-sdk-nightly-$(date --iso-8601)

echo "Working in $TEMP_DIR"
cd $TEMP_DIR

echo 'Downloading files'
mkdir src
cd src
git clone https://github.com/luwrain/base.git &> ../clone-base.log
cd base/scripts
./lwr-checkout &> ../../../checkout.log
./lwr-distr-src "$TEMP_DIR/$SRC_RES_DIR"

echo 'Compiling sources'
./lwr-prepare  &> ../../../prepare.log
./lwr-build &> ../../../build.log
./lwr-distr-linux "$TEMP_DIR/$LINUX_RES_DIR"
./lwr-distr-iso "$TEMP_DIR/$ISO_RES_DIR"
./lwr-distr-sdk "$TEMP_DIR/$SDK_RES_DIR" &> ../../../sdk.log

cd "$TEMP_DIR"
for i in $SRC_RES_DIR $LINUX_RES_DIR $ISO_RES_DIR; do
    tar -c $i/ > $i.tar
    echo "Compressing $i.tar"
    gzip $i.tar &> /dev/null
    md5sum --binary $i.tar.gz >> md5sum.txt
    sha1sum "$i.tar.gz" >> sha1sum.txt
done
zip -r $SDK_RES_DIR.zip $SDK_RES_DIR  
md5sum --binary $SDK_RES_DIR.zip >> md5sum.txt
sha1sum $SDK_RES_DIR.zip >> sha1sum.txt

echo 'OK!'
