#!/bin/bash -e

. init.sh

DIST_DIR="$1"
DEST_DIR="$2"
[ -z "$DIST_DIR" ] && echo "$THIS: no source dir given" >&2 && exit 1
[ -z "$DEST_DIR" ] && echo "$THIS: no dest dir given" >&2 && exit 1

mkdir -p "$DEST_DIR"
cp -r "$DIST_DIR/." "$DEST_DIR"
lwr-custom-base-win "$DEST_DIR" publisher
cd "$DEST_DIR"

pushd 64/jar > /dev/null
for k in books publisher studio player pim edu-algo app-news app-contacts app-commander app-mail app-telegram app-twitter app-vk; do
    rm -f luwrain-$k.jar
done
popd > /dev/null

pushd 64/lib > /dev/null
rm -f javax.mail*.jar junit*.jar twitter*.jar vk-sdk*.jar
popd > /dev/null

pushd 64/data/properties > /dev/null
sed -i -e s/'org.luwrain.core.shell.desktop.Desktop'/'org.luwrain.app.publisher.App'/ luwrain.properties
popd > /dev/null

pushd 64/data/js > /dev/null
rm -f studio-*.js reader-ms*.js edu-*.js clock*.js
popd > /dev/null

lwr-custom-base-win-legacy $DEST_DIR publisher

for i in 64 32; do
    lwr-custom-base-win-installer publisher $i $DEST_DIR/$i $DEST_DIR/installer$i
done
