#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh


rm -rf /tmp/st
mkdir /tmp/st

DEST_DIR=/tmp/st

lwr-dist-linux "$DEST_DIR/linux"
lwr-dist-win "$DEST_DIR/win"
cd "$DEST_DIR"
rm -rf win/installer-x64

for i in win linux; do
    pushd $i/x64/rhvoice > /dev/null
    pushd data/languages > /dev/null
rm -rf Brazilian-Portuguese Esperanto Georgian Kyrgyz Tatar Ukrainian
popd > /dev/null
pushd data/voices > /dev/null
rm -rf alan elena anatol anna azamat bdl clb irina Leticia-F123 natalia natia nazgul slt spomenka talgat
popd > /dev/null
    popd > /dev/null
    touch $i/x64/standalone
    rm -f $i/x64/ReleaseInfo.txt $i/x64/LICENSE*
done


cat <<EOF > rename

CUSTOM_NAME="\$1"

pushd win/x64 > /dev/null
mv luwrain.exe \$CUSTOM_NAME.exe
mv luwrain.ico \$CUSTOM_NAME.ico
pushd app > /dev/null
mv luwrain.cfg \$CUSTOM_NAME.cfg
popd > /dev/null
popd > /dev/null

pushd linux/x64 > /dev/null
mv luwrain \$CUSTOM_NAME
mv luwrain.ico \$CUSTOM_NAME
    sed -i -e s:' ./luwrain':" ./\$CUSTOM_NAME": luwrain-speechd*
    mv luwrain-speechd \$CUSTOM_NAME-speechd
    mv luwrain-speechd-ru \$CUSTOM_NAME-speechd-ru
popd > /dev/null
EOF

chmod 755 rename
