#!/bin/bash -e

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"

for ARCH in $LINUX_ARCH; do
    mkdir -p $DEST_DIR/$ARCH""

    cd "$SCRIPTS_DIR"
    ./lwr-distr-linux-common "$DEST_DIR/$ARCH"

    cd "$DEST_DIR/$ARCH"
    cp -r "$SRC_DIR/precompiled/linux-x86-$ARCH/." .

    cp -r "$SRC_DIR/base/txt/linux/." .
    cat <<EOF > ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
$ARCH-bit release for GNU/Linux
EOF

done
