#!/bin/bash -e

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p $DEST_DIR

cd "$SRC_DIR/base/scripts"
./lwr-distr-win-common "$DEST_DIR"
cd $DEST_DIR
cp -r "$SRC_DIR/precompiled/windows/." .
cp -r "$SRC_DIR/base/txt/win-nojre/." .
cat <<EOF > ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
Release for Microsoft Windows
You need an external Java virtual machine for running LUWRAIN on your computer
EOF

#FIXME:speech settings
#FIXME:launch script
