#!/bin/bash -e

. init.sh

./lwr-update-lib-dirs
./lwr-mk-lib-refs
./lwr-sqlite

for i in scripts properties; do
    mkdir -p "$SRC_DIR/data/$i"
done

for i in $TAKE_SCRIPTS; do
    cp -r "$SRC_DIR/$i/scripts/." "$SRC_DIR/data/scripts"
done

for i in $TAKE_PROPERTIES; do
    cp -r "$SRC_DIR/$i/properties/." "$SRC_DIR/data/properties"
done

cat  <<EOF > "$SRC_DIR/data/properties/$PROPERTIES_FILE"
luwrain.version = Nightly $(date --iso-8601)
EOF

cat <<EOF > "$SRC_DIR/data/DESKTOP.ru.txt"
LUWRAIN (отладочная версия)
Дата релиза: $(date --iso-8601)
Авторы: Алексей Голошумов и Михаил Пожидаев
Веб-сайт: http://luwrain.org/
EOF

#Добро пожаловать в LUWRAIN!
#
#Вы находитесь на рабочем столе пользовательской среды LUWRAIN. Начните
#работу при помощи одного из пунктов ниже или через главное
#меню. Главное меню открывает клавиша на клавиатуре, которая
#располагается обычно второй слева в нижнем ряду. Обратите также,
#пожалуйста, внимание, что комбинация клавиш Alt+X всегда открывает
#командную строку для быстрого доступа к различным функциям нашей
#системы.
