#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p $DEST_DIR
cd $DEST_DIR

ARCH=64
mkdir 64
cd 64
cp -r $SRC_DIR/binary/win$ARCH/. .
lwr-basedirs-win $DEST_DIR/64
cp -r "$SRC_DIR/base/txt/windows/." .
cat <<EOF > ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
x64 release for Microsoft Windows (64-bit)
EOF
cd ..

lwr-custom-base-win-legacy $DEST_DIR
cat <<EOF > 32/ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
x86 release for Microsoft Windows (32-bit)
EOF

lwr-win-installer luwrain 64 $DEST_DIR/64 $DEST_DIR/installer64
lwr-win-installer luwrain 32 $DEST_DIR/32 $DEST_DIR/installer32
