#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

# TODO: rename this script to lwr-win-32bit

. init.sh

[ -z "$1" ] && echo "$THIS: No dir to work given" >&2 && exit 1
FLAVOR="$2"

cd "$1"

cp -r "$SRC_DIR/binary/legacy-win32" 32
for i in jar lib data rhvoice ; do
    cp -r "64/$i" 32/app/
done
if [ -e 64/standalone ]; then
    echo >> 32/app/standalone
fi

if [ -n "$FLAVOR" ]; then
    cat 64/$FLAVOR.ico > 32/$FLAVOR.ico
    pushd 32 > /dev/null
    mv luwrain.exe $FLAVOR.exe
    rm -f luwrain.ico
    pushd app > /dev/null
    mv luwrain.cfg $FLAVOR.cfg
    popd > /dev/null
    popd > /dev/null
fi
