#!/bin/bash -e

. init.sh

DEST_DIR="$1"
CUSTOM_NAME="$2"
[ -z "$DEST_DIR" ] && echo "$THIS: No dest directory" >&2 && exit 1
[ -z "$CUSTOM_NAME" ] && echo "$THIS: No custom name" >&2 && exit 1

cd "$DEST_DIR"

mkdir tmp
pushd tmp > /dev/null
git clone https://github.com/luwrain/registry.git/
mkdir registry.linux
pushd registry > /dev/null
git branch $CUSTOM_NAME origin/$CUSTOM_NAME
git checkout $CUSTOM_NAME
./lwr-reg-compile linux ../registry.linux
popd > /dev/null
rm -rf registry
popd > /dev/null

for i in $LINUX_ARCH; do
    pushd $i > /dev/null
    rm -f luwrain
cat <<EOF > "$CUSTOM_NAME
#!/bin/bash -e

# To suppress warnings about unavailable accessibility services
export NO_AT_BRIDGE=1

cd lib/app
exec ../"$CUSTOM_NAME" "$@"
EOF
    chmod 755 "$CUSTOM_NAME"
    rm -f *.txt *speechd*
    popd > /dev/null
pushd $I/lib > /dev/null
mv luwrain "$CUSTOM_NAME"
mv luwrain.png "$CUSTOM_NAME"
popd > /dev/null
    pushd $i/lib/app > /dev/null
    mv luwrain.cfg "$CUSTOM_NAME".cfg
    touch standalone
    pushd data > /dev/null
    rm -f registry*
    cp -r "$DEST_DIR/tmp/registry.linux/." .
    popd > /dev/null
        pushd rhvoice/data/languages > /dev/null
    rm -rf Brazilian-Portuguese Esperanto Georgian Kyrgyz Tatar Ukrainian
    popd > /dev/null
    pushd rhvoice/data/voices > /dev/null
    rm -rf alan aleksandr anatol anna azamat bdl clb irina Leticia-F123 natalia natia nazgul slt spomenka talgat
    popd > /dev/null
    popd > /dev/null
done
rm -rf tmp
echo OK

