#!/bin/bash -e

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1
cd $DEST_DIR

mkdir -p jar
for i in lib data; do
    cp -r "$SRC_DIR/$i" "$i"
done
rm -rf data/properties data/scripts

#jars
cp "$SRC_DIR/luwrain/jar/luwrain.jar" jar
for i in $WIN_COMPONENTS; do
    cp "$SRC_DIR/$i/jar/luwrain-$i.jar" jar
done
for i in $WIN_APPS; do
    cp "$SRC_DIR"/app-$i/jar/luwrain-app-$i.jar jar
done
for i in $WIN_LANGS; do
    cp "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar
done
for i in $WIN_EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done

pushd "$SRC_DIR/registry" > /dev/null
./lwr-reg-compile win "$DEST_DIR/data"
popd > /dev/null

#JavaScript
cp -r "$SRC_DIR/extensions/js" data/js
#Text extensions
cp -r "$SRC_DIR/extensions/text" data/text

#properties
mkdir data/properties
for i in $WIN_PROPERTIES; do
    cp -r "$SRC_DIR/$i/properties/." data/properties
done
cat <<EOF > data/properties/release.properties
luwrain.version = $VERSION
luwrain.registry.version = $REGISTRY_VERSION
luwrain.build.date = $(date -I)
EOF

# luwrain.bat
cat <<EOF > luwrain.bat
rem Runs LUWRAIN with the locally installed (not embedded) Java SE Runtime Environment
rem This can be useful for debug purposes

javaw -cp jar\luwrain-base.jar;jar\luwrain.jar org.luwrain.core.Init
EOF
