#!/bin/bash -e
# The script to fetch the source code of LUWRAIN

. init.sh

lwr-list-repos | while read l; do
    if [ "$l" != base ]; then
	echo Cloning $l
	git clone https://github.com/luwrain/$l.git 2> /dev/null
    fi
done

echo 'Downloading binary data'
wget -q 'http://download.luwrain.org/compilation/binary.tar.gz'
tar xf binary.tar.gz
mv binary/lib .
mkdir data
mv binary/sounds data
rm -f binary.tar.gz

lwr-update-lib-dirs
lwr-mk-lib-refs
lwr-ant-gen-all

echo 'Your sources ready!'
