#!/bin/bash -e

THIS="${0##*/}"

VERSION="$1"

[ -z "$VERSION" ] && echo "$THIS:no version given" >&2 && exit 1

./lwr-distr-src

cd /tmp
cp -r luwrain-src luwrain-data-$VERSION
tar -c luwrain-data-$VERSION/ | gzip > luwrain-data-$VERSION.tar.gz
md5sum --binary luwrain-data-$VERSION.tar.gz > luwrain-data-$VERSION.tar.gz.md5
mv luwrain-src luwrain-$VERSION
tar -c luwrain-$VERSION/ | gzip > luwrain-$VERSION.tar.gz
