#!/bin/bash -e
# Copyright 2012-2021 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

for i in base luwrain; do
    cd "$i"
    ant -emacs
    cd ..
done

for i in $COMPONENTS; do
    cd "$i"
    ant -emacs
    cd ..
done

for i in $APPS; do
    cd app-$i
    ant -emacs
    cd ..
done

cd extensions
for i in $EXTENSIONS; do
    cd $i
    ant -emacs
    cd ..
done
cd ..

cd i18n
for i in $LANGS; do
    cd $i
    ant -emacs
    cd ..
done
cd ..

echo Everything is built successfully!
