#!/bin/bash -e
# Copyright 2012-2021 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

DIST_DIR="$1"
DEST_DIR="$2"

[ -z "$DIST_DIR" ] && echo "$THIS: no source dir given" >&2 && exit 1
[ -z "$DEST_DIR" ] && echo "$THIS: no dest dir given" >&2 && exit 1

mkdir -p "$DEST_DIR"
cp -r "$DIST_DIR/." "$DEST_DIR"
lwr-custom-base-linux "$DEST_DIR" dm
cd "$DEST_DIR"

for i in $LINUX_ARCH; do

    pushd $i/lib/app/jar > /dev/null
    for k in books studio pim edu-algo app-news app-contacts app-commander app-mail app-telegram app-twitter app-vk; do
	rm -f luwrain-$k.jar
    done
    rm -f *tsulib*.jar *-edu*.jar
    popd > /dev/null

    pushd $i/lib/app/lib > /dev/null
    rm -f junit*.jar twitter*.jar vk-sdk*.jar
    popd > /dev/null

    pushd $i/lib/app/data/properties > /dev/null
    sed -i -e s/'org.luwrain.core.shell.desktop.Desktop'/'ru.directmedia.app.App'/ luwrain.properties
    popd > /dev/null

    pushd $i/lib/app/data/js > /dev/null
    rm -f studio-*.js reader-ms*.js edu-*.js clock*.js
    popd > /dev/null

    pushd $i/lib/app/data/sounds/schemes/pragmatic > /dev/null
    rm -f startup.wav
    wget -q http://download.luwrain.org/media//startup/dm.wav
    mv dm.wav startup.wav
    popd > /dev/null

done
