#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

lwr-list-repos | while read l; do
    if [ "$l" != luwrain ]; then
	cat luwrain/AUTHORS > $l/AUTHORS
	cat luwrain/LICENSE > $l/LICENSE
    fi
done
