#!/bin/bash -e

. init.sh
cd "$SRC_DIR"

for i in base luwrain; do
    cd "$i"
    ant
    cd ..
done

for i in $COMPONENTS; do
    cd "$i"
    ant
    cd ..
done

for i in $APPS; do
    cd app-$i
    ant
    cd ..
done

cd extensions
for i in $EXTENSIONS; do
    cd $i
    ant
    cd ..
done
cd ..

cd i18n
for i in $LANGS; do
    cd $i
    ant
    cd ..
done
cd ..

echo Everything is built successfully!
