#!/bin/bash -e

. init.sh

if [ -n "$1" ]; then
    SRC_DEST_DIR="$1"
else
    SRC_DEST_DIR=/tmp/luwrain-src
fi

[ -e "$SRC_DEST_DIR" ] && echo "$THIS:$SRC_DEST_DIR already exists" >&2 && exit 1

mkdir -p "$SRC_DEST_DIR"
cp -r . "$SRC_DEST_DIR"

for i in AUTHORS LICENSE; do
find "$SRC_DEST_DIR" -name $i -delete
done

for i in AUTHORS LICENSE README.md; do
    cp luwrain/$i "$SRC_DEST_DIR"
done

cd "$SRC_DEST_DIR"
ls | while read l; do
    if [ -e "$l/.git" ]; then
rm -rf "$l/.git"
fi
done 

rm -rf apptemplate-win-32 precompiled
find -name .gitignore -delete

