#!/bin/bash -e

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"

cd "$SRC_DIR/base/scripts"
./lwr-distr-linux-common "$DEST_DIR"

cd "$DEST_DIR"
cp -r "$SRC_DIR/linux/src/jni" jni-src
pushd jni-src > /dev/null
rm -f *.so *.o .gitignore
popd > /dev/null
zip -r jni-src.zip jni-src/ > /dev/null
rm -rf jni-src

cp -r "$SRC_DIR/base/txt/linux-nojre/." .
cat <<EOF > ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
Release for GNU/Linux
You need an external Java virtual machine for running LUWRAIN on your computer
EOF
