#!/bin/bash -e

. init.sh

ORIG_DEST_DIR="$1"
[ -z "$ORIG_DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1

for LANG in $ISO_LANGS; do
    for ARCH in $ISO_ARCH; do
	DEST_DIR=$ORIG_DEST_DIR/ubuntu-16.04-"$ARCH"bit-$LANG
	for i in profile etc opt bin; do
	    mkdir -p "$DEST_DIR/$i"
	done
cat <<EOF > "$DEST_DIR/bin/luwrain"
#!/bin/bash -e

exec /opt/luwrain/luwrain "\$@"
EOF
	chmod 755 "$DEST_DIR/bin/luwrain"
	OPT="$DEST_DIR/opt"
	mkdir "$OPT/greeter"
	cp -r "$SRC_DIR/linux/greeter/langs/$LANG/." "$OPT/greeter"
	mkdir -p "$OPT/luwrain"
	lwr-basedirs-iso $ARCH $LANG "$OPT/luwrain"
    done
done
