#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "ERROR: $THIS: No destination directory" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir "$DEST_DIR"
cd "$DEST_DIR"

jars()
{
    find "$1" -iname '*.jar' |
    while read l; do
	echo -n "$l:"
    done
    echo
}

javadoc -classpath "$(jars "$SRC_DIR"/release/lib)" \
	$(find "$SRC_DIR"/{base,luwrain,javafx-interaction,io,pim}/src/main/java -iname '*.java')
