#!/bin/bash -e

. init.sh
cd "$SRC_DIR/registry"

DEST_DIR="$1"
if [ -z "$DEST_DIR" ]; then
    DEST_DIR=/tmp/lwr-registry
fi

mkdir -p "$DEST_DIR/org/luwrain"
cp -r base/. i18n.ru/. "$DEST_DIR/org/luwrain"
find "$DEST_DIR/org/luwrain" -type d -exec touch '{}'/strings.txt \;
find "$DEST_DIR/org/luwrain" -type d -exec touch '{}'/integers.txt \;
find "$DEST_DIR/org/luwrain" -type d -exec touch '{}'/booleans.txt \;

