#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

ARCH=x64

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p $DEST_DIR
cd $DEST_DIR

mkdir $ARCH
cd $ARCH
lwr-basedirs-win $DEST_DIR/$ARCH
cat <<EOF > ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
$ARCH release for Microsoft Windows
EOF
cd ..

lwr-win-installer luwrain 64 $DEST_DIR/$ARCH $DEST_DIR/installer-$ARCH
