#!/bin/bash -e

. init.sh

TAG="$1"
[ -z "$TAG" ] && echo "$THIS:no tag given" >&2 && exit 1

for i in $GITS; do
    echo "Tagging $i"
    pushd $i  > /dev/null
    git tag "$TAG" > /dev/null
    git push --tags origin > /dev/null
    popd		 > /dev/null
done			

for i in $APPS; do
    echo "Tagging app-$i"
    pushd app-$i > /dev/null
    git tag "$TAG" > /dev/null
    git push --tags origin > /dev/null
popd		 > /dev/null
done

echo OK
