#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

JRE=jre18-linux-x64
ARCH=x64

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS: no destination directory" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"
cd "$DEST_DIR"

wget -q https://download.luwrain.org/compilation/$JRE.tar.xz
tar xf $JRE.tar.xz
mv $JRE $ARCH
rm -f $JRE.tar.xz
lwr-basedirs-linux "$DEST_DIR/$ARCH/"
mv $ARCH/jar/luwrain-base*.jar $ARCH/lib/app/luwrain-base.jar

wget -q https://download.luwrain.org/compilation/rhvoice-data.tar.xz
tar xf rhvoice-data.tar.xz
cp -r rhvoice $ARCH/rhvoice
rm -rf rhvoice*

cat <<EOF > $ARCH/ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
$ARCH release for GNU/Linux
EOF
