#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

DIR="$(pwd)"
DEST_DIR="$DIR/debian/luwrain/usr/share/luwrain"

cd base/scripts
mkdir -p "$DEST_DIR/bin"

cat <<EOF > "$DEST_DIR/bin/luwrain"
#!/bin/bash -e
# Runs the LUWRAIN platform
# Copyright 2022 Michael Pozhidaev <msp@luwrain.org>

cd /usr/share/luwrain
exec java --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.web -jar jar/luwrain-base.jar "\$@"
EOF

cat <<EOF > "$DEST_DIR/bin/lwr"
#!/bin/bash -e
# Runs the LUWRAIN platform blocking any output
# Copyright 2022 Michael Pozhidaev <msp@luwrain.org>

exec luwrain "\$@" > /dev/null 2>&1
EOF
chmod 755 "$DEST_DIR/bin/luwrain" "$DEST_DIR/bin/lwr"

./lwr-basedirs-linux "$DEST_DIR"
rm -f "$DEST_DIR"/jar/javafx-*.jar
