#!/bin/bash -e

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1
cd "$DEST_DIR"

mkdir -p jar
for i in data lib; do
        cp -r "$SRC_DIR/$i" .
done
rm -rf data/properties data/scripts

#Jars
cp "$SRC_DIR/luwrain/jar/luwrain.jar" jar
for i in $LINUX_COMPONENTS; do
    cp "$SRC_DIR/$i/jar/luwrain-$i.jar" jar
done
for i in $LINUX_APPS; do
    cp "$SRC_DIR"/app-$i/jar/luwrain-app-$i.jar jar
done
for i in $LINUX_LANGS; do
    cp "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar
done
for i in $LINUX_EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done

for i in $LINUX_EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done
if [ -d ~/.luwrain/dev/jars/ ]; then
    for i in ~/.luwrain/dev/jars/*; do
	cat $i > jar/"$(basename "$i")"
    done
fi

#registry
pushd "$SRC_DIR/registry" > /dev/null
./lwr-reg-compile linux "$DEST_DIR/data"
popd > /dev/null

#JavaScript
cp -r "$SRC_DIR/extensions/js" data/js
#Text extensions
cp -r "$SRC_DIR/extensions/text" data/text

#properties
mkdir data/properties
for i in $LINUX_PROPERTIES; do
    cp -r "$SRC_DIR/$i/properties/." data/properties
done
cat <<EOF > data/properties/release.properties
luwrain.version = $VERSION
luwrain.registry.version = $REGISTRY_VERSION
luwrain.build.date = $(date -I)
EOF

#scripts
mkdir -p data/scripts
for i in $LINUX_SCRIPTS; do
    cp -r "$SRC_DIR/$i/scripts/." data/scripts
done
chmod +x data/scripts/*
