#!/bin/bash -e
# Copyright 2012-2022 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

if ! [ -e /tmp/binary.tar.gz ]; then
    wget -q 'http://download.luwrain.org/compilation/binary.tar.gz'
else
    cat /tmp/binary.tar.gz > binary.tar.gz
fi


tar xf binary.tar.gz
mv binary/lib .
if ! java -version 2>&1 | egrep -q 'version "1.8.'; then
    for i in /usr/share/openjfx/lib/*.jar; do
	ln -s $i lib/$(basename $i)
    done
fi
mkdir data
mv binary/sounds data
rm -f binary.tar.gz
lwr-ant-gen-all
