#!/bin/bash -e

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p $DEST_DIR
cd $DEST_DIR

ARCH=64
# Portable
mkdir $ARCH
cd $ARCH
cp -r "$SRC_DIR/binary/win$ARCH/." .
lwr-basedirs-win "$DEST_DIR/$ARCH"
cp -r "$SRC_DIR/base/txt/windows/." .
cat <<EOF > ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
$ARCH-bit release for Microsoft Windows
EOF
cd ..

lwr-custom-base-win-legacy $DEST_DIR
cat <<EOF > 32/ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
32-bit release for Microsoft Windows
EOF

# Installer
mkdir installer$ARCH
cd installer$ARCH
cp -r "$SRC_DIR/binary/wininstaller/." .
mkdir -p iss-fix/x$ARCH/Luwrain
cp -r "$SRC_DIR/binary/win$ARCH/." ./iss-fix/x$ARCH/Luwrain/
lwr-basedirs-win "$DEST_DIR/installer$ARCH/iss-fix/x$ARCH/Luwrain"
cp -r "$SRC_DIR/windows/installer/nightly/." ./
cp "$SRC_DIR/windows/installer"/*.iss iss-fix
sed -i -e s/LUWRAIN_VERSION/$VERSION/ iss-fix/*.iss
cd ..
