#!/bin/bash -e
# Copyright 2012-2021 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

lwr-list-repos | while read l; do
    pushd "$l" > /dev/null
    if git status --porcelain | egrep -q '^[A ][DM]'; then
	echo "$l has uncommitted changes"
    fi
        if git status --porcelain | egrep -q '^\?. '; then
	echo "$l has unregistered files"
    fi
    popd > /dev/null
done
