#!/bin/bash -e

. init.sh

mkdir -p ~/luwrain

cd ~/luwrain
mkdir jar
for i in sqlite lib data; do
    ln -s "$SRC_DIR/$i" $i
done 
ln -s "$SRC_DIR/linux/luwrain.sh" ~/luwrain/luwrain.sh
mkdir -p registry/org/luwrain 
cp -r "$SRC_DIR/registry/base/." registry/org/luwrain
mkdir -p i18n/ru/org/luwrain
cp -r "$SRC_DIR/registry/i18n.ru/." i18n/ru/org/luwrain

#Jars
ln -s "$SRC_DIR/luwrain/jar/luwrain.jar" jar/luwrain.jar
for i in base linux pim doctree interaction-javafx network; do
    ln -s "$SRC_DIR/$i/jar/luwrain-$i.jar" jar/luwrain-$i.jar
done 

for i in $APPS; do
ln -s "$SRC_DIR"/app-$i/jar/luwrain-app-$i.jar jar/luwrain-app-$i.jar
done

for i in $LANGS; do
ln -s "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar/luwrain-lang-$i.jar
done

for i in $EXTENSIONS; do
ln -s "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar/luwrain-ext-$i.jar
done
