#!/bin/bash -e

. init.sh

DEST_DIR=$SRC_DIR/hsqldb
SQLTOOL=$SRC_DIR/lib/sqltool.jar
PREFIX=jdbc:hsqldb:file:
BASEURL=$PREFIX$DEST_DIR/
SCRIPTSDIR=$SRC_DIR/pim/sql

mkdir -p "$DEST_DIR"

if [ "$1" == --help ]; then
    java -jar "$SQLTOOL" --help
    exit 0
fi

#if [ "$1" == --test ]; then
#    URL="$PREFIX$2"
#    java -jar "$SQLTOOL" \
#	--inlineRc=url="$URL",user=sa,password= 
#    exit 0
#fi

for i in $DBS; do
    URL="$BASEURL$i"
    echo "Processing $URL"
    java -jar "$SQLTOOL" \
	--inlineRc=url="$URL",user=sa,password= \
	"$SCRIPTSDIR/$i.sql"
    rmdir $DEST_DIR/$i.tmp
done
