#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

ARCH=x64

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "ERROR: $THIS: No destination directory" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"
cd "$DEST_DIR"

lwr-basedirs-linux "$DEST_DIR/$ARCH/"
mv $ARCH/jar "$ARCH/lib"

mkdir "$ARCH"/bin
cat <<EOF > "$ARCH/bin/luwrain"
#!/bin/bash -e
# Copyright $(date +%Y) Michael Pozhidaev <msp@luwrain.org>

THIS="\${0##*/}"

cd "\$(dirname "\$0")"/..

if [ -n "\$JAVA_HOME" ] && [ -x "\$JAVA_HOME/bin/java" ]; then
exec "\$JAVA_HOME/bin/java" -cp "lib/*" org.luwrain.core.Init "\$@"
fi
EOF
chmod 755 "$ARCH/bin/luwrain"

wget -q https://download.luwrain.org/compilation/rhvoice-data.tar.xz
tar xf rhvoice-data.tar.xz
cp -r rhvoice $ARCH/rhvoice
rm -rf rhvoice*

cp -r "$SRC_DIR/base/txt/linux/." "$ARCH"
cp "$SRC_DIR/base/LICENSE" "$ARCH/LICENSE.en.txt"

cat <<EOF > $ARCH/ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
Release for GNU/Linux
EOF
