#!/bin/bash -e

. init.sh

DEST_DIR=/tmp/luwrain-linux

mkdir -p $DEST_DIR

cd $DEST_DIR
mkdir jar news
cp -r "$SRC_DIR/linux/src/jni" jni
cp -r "$SRC_DIR/data" data
cp -r "$SRC_DIR"/lib lib
cp  "$SRC_DIR/linux/luwrain.sh" luwrain.sh
cp -r "$SRC_DIR/linux/setup.sh" setup.sh
cp -r "$SRC_DIR/registry/default.linux" registry
cp -r "$SRC_DIR/registry/default.news.ru" news/ru

#Jars
#cp "$SRC_DIR/base/jar/luwrain-base.jar" jar
cp "$SRC_DIR/luwrain/jar/luwrain.jar" jar
#cp "$SRC_DIR/linux/jar/luwrain-linux.jar" jar
#cp "$SRC_DIR/pim/jar/luwrain-pim.jar" jar

for i in base linux pim doctree interaction-javafx network; do
    cp "$SRC_DIR/$i/jar/luwrain-$i.jar" jar
done

for i in $APPS; do
    cp "$SRC_DIR"/app-$i/jar/luwrain-app-$i.jar jar
done

for i in $LANGS; do
    cp "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar
done

for i in $EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done

cp -r "$SRC_DIR"/hsqldb .

cat  <<EOF > "$LUWRAIN_PROPERTIES"
luwrain.version = Nightly $(date --iso-8601)
EOF

#Cleaning
cd jni
rm -f *.so *.o .gitignore
cd ..
