#!/bin/bash -e
# Copyright 2012-2021 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

DIST_DIR="$1"
DEST_DIR="$2"
[ -z "$DIST_DIR" ] && echo "$THIS: no source dir given" >&2 && exit 1
[ -z "$DEST_DIR" ] && echo "$THIS: no dest dir given" >&2 && exit 1

mkdir -p "$DEST_DIR"
cp -r "$DIST_DIR/." "$DEST_DIR"
lwr-custom-base-win $DEST_DIR books
cd "$DEST_DIR"

pushd 64/jar > /dev/null
for k in browser publisher studio pim packs; do
    rm -f luwrain-$k.jar
done
rm -f luwrain-app* *dm*.jar *tsulib*.jar *-edu*.jar
popd > /dev/null

pushd 64/lib > /dev/null
rm -f javax.mail*.jar junit*.jar twitter*.jar vk-sdk*.jar
popd > /dev/null

pushd 64/data/js > /dev/null
rm rm commander*.js -f studio-*.js reader-ms*.js clock*.js linux*.js  math*.js message*.js music*.js notepad*.js pim*.js pm*.js tsulib*.js util-keyboard*.js web-cbrf*.js web-ddg*.js wi-disks*.js mail.j *edu*.jss
popd > /dev/null

pushd 64/data/properties > /dev/null
sed -i -e s/'org.luwrain.core.shell.desktop.Desktop'/'org.luwrain.app.reader.App'/ luwrain.properties
popd > /dev/null

pushd 64/data/sounds/schemes/pragmatic > /dev/null
rm -f startup.wav
wget -q http://download.luwrain.org/compilation/startup-books.wav
mv startup-books.wav startup.wav
popd > /dev/null

lwr-custom-base-win-legacy $DEST_DIR books

for i in 64 32; do
    lwr-win-installer books $i $DEST_DIR/$i $DEST_DIR/installer$i
done
