#!/bin/bash -e

. init.sh
cd "$SRC_DIR"

check-repo()
{
    cd "$1"
    if git status --porcelain | egrep -q '^[A ][DM]'; then
	echo "$1 has uncommitted changes"
    fi
    cd ..
}

for i in luwrain base doctree linux windows registry interaction-javafx pim network; do
    check-repo "$i"
done

for i in $APPS; do
    check-repo "app-$i"
done
