#!/bin/bash -e

. init.sh
cd "$SRC_DIR"

for i in $GITS; do
    echo "Pushing $i"
    pushd $i  > /dev/null
    git push origin "$@" &> /dev/null
    popd		 > /dev/null
done			

for i in $APPS; do
    echo "Pushing app-$i"
    pushd app-$i > /dev/null
git push origin "$@" &> /dev/null
popd		 > /dev/null
done

echo OK
