#!/bin/bash -e
# Copyright 2012-2021 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1
cd "$DEST_DIR"

mkdir -p jar
for i in data lib; do
        cp -r "$SRC_DIR/$i" .
done
mv lib/luwrain*.jar jar
rm -rf data/properties data/scripts

#Jars
cp "$SRC_DIR/luwrain/jar/luwrain.jar" jar
for i in $LINUX_COMPONENTS; do
    cp "$SRC_DIR/$i/jar/luwrain-$i.jar" jar
done
for i in $LINUX_APPS; do
    cp "$SRC_DIR"/app-$i/jar/luwrain-app-$i.jar jar
done
for i in $LINUX_LANGS; do
    cp "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar
done
for i in $LINUX_EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done
for i in $LINUX_EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done

#Registry
pushd "$SRC_DIR/registry" > /dev/null
./lwr-reg-compile linux "$DEST_DIR/data"
popd > /dev/null

#JavaScript
cp -r "$SRC_DIR/extensions/js" data/js

#Properties
mkdir data/properties
for i in $LINUX_PROPERTIES; do
    cp -r "$SRC_DIR/$i/properties/." data/properties
done
cat <<EOF > data/properties/release.properties
luwrain.version = $VERSION
luwrain.registry.version = $REGISTRY_VERSION
luwrain.build.date = $(date -I)
EOF

#Scripts
mkdir -p data/scripts
for i in $LINUX_SCRIPTS; do
    cp -r "$SRC_DIR/$i/scripts/." data/scripts
done
chmod +x data/scripts/*
