#!/bin/bash -e
# The script to fetch Luwrain source code

COMPONENTS='luwrain linux pim i18n registry windows doctree extensions interaction-javafx network'

. init.sh
cd "$SRC_DIR"

for i in $COMPONENTS; do
    git clone https://github.com/luwrain/$i.git
done

for i in $APPS; do
git clone https://github.com/luwrain/app-$i.git
done

wget http://download.luwrain.org/data/luwrain-data.zip
wget http://download.luwrain.org/lib/luwrain-lib.zip
wget http://download.luwrain.org/ubuntu/precompiled/luwrain-ubuntu-precompiled.zip

for i in data lib ubuntu-precompiled; do
    unzip luwrain-$i.zip
    rm -f luwrain-$i.zip
done

echo 
echo Everything is fetched successfully!
