#!/bin/bash -e

. init.sh

DIST_DIR="$1"
DEST_DIR="$2"
[ -z "$DIST_DIR" ] && echo "$THIS: no source dir given" >&2 && exit 1
[ -z "$DEST_DIR" ] && echo "$THIS: no dest dir given" >&2 && exit 1

mkdir -p "$DEST_DIR"
cp -r "$DIST_DIR/." "$DEST_DIR"

lwr-custom-base-win "$DEST_DIR" anatomy

cd "$DEST_DIR"
for i in $WIN_ARCH; do
    pushd $i/jar > /dev/null
    for k in books publisher studio player pim app-news app-contacts app-commander app-mail app-telegram app-twitter app-vk; do
	rm -f luwrain-$k.jar
    done
    popd > /dev/null
    pushd $i/lib > /dev/null
    rm -f javamail*.jar javaxmail*.jar junit*.jar twitter*.jar vk-sdk*.jar
    popd > /dev/null
    pushd $i/data/js > /dev/null
    rm -f studio-*.js reader-ms*.js edu-*.js clock*.js
    popd > /dev/null
done
echo OK
