#!/bin/bash -e

. init.sh

THIS="${0##*/}"

DEST_DIR="$1"
PKG_DIR="$2"
[ -z "$DEST_DIR" ] && echo "$THIS:DEST_DIR not given" >&2 && exit 1
[ -z "$PKG_DIR" ] && echo "$THIS:PKG_DIR not given" >&2 && exit 1

if [ -d "$DEST_DIR" ]; then
    rm -rf "$DEST_DIR"
fi

mkdir -p $DEST_DIR

cd $DEST_DIR
mkdir 32
cd 32

cp -r "$SRC_DIR/apptemplate-win-32/." .
for i in data lib jar i18n registry sqlite; do
    cp -r "$PKG_DIR/32/$i" ./app
done

cp -r "$SRC_DIR/txt/win-app/. " .

cat <<EOF > ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
32-bit release for Microsoft Windows
EOF
