#!/bin/bash -e

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS:no destination directory given" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p $DEST_DIR
cd $DEST_DIR
for ARCH in $WIN_ARCH; do
    mkdir $ARCH
    pushd $ARCH > /dev/null

    pushd "$SRC_DIR/base/scripts" > /dev/null
    ./lwr-distr-win-common "$DEST_DIR/$ARCH"
    popd > /dev/null

    cp -r "$SRC_DIR/precompiled/windows/." .

    popd > /dev/null
done
