#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

lwr-list-repos | while read l; do
    echo "Setting credential.helper to store for $l"
    pushd $l  > /dev/null
    git config credential.helper store
    popd		 > /dev/null
done			

echo OK
